name: Dart Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart and Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'

      - name: Install dependencies
        run: |
          flutter pub get
          sudo apt-get update
          sudo apt-get install -y lib32stdc++6

      - name: Analyze project source
        run: dart analyze

      - name: Flutter test
        run: flutter test

      - name: Build Android APK and app bundle
        run: |
          flutter build apk
          flutter build appbundle

      - name: Upload Dart analysis results
        uses: actions/upload-artifact@v2
        with:
          name: analysis-results
          path: analysis_results

  download-analysis:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Dart analysis results
        uses: actions/download-artifact@v2
        with:
          name: analysis-results
