name: Dart Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          dart-sdk-version: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lib32stdc++6  # Install lib32stdc++6
          flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Upload Dart analysis results
        uses: actions/upload-artifact@v2
        with:
          name: analysis-results
          path: analysis_results

  download-analysis:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Dart analysis results
        uses: actions/download-artifact@v2
        with:
          name: analysis-results
